import { useEffect, useMemo, useState } from 'react'
import { ArrowUpRight, BarChart3, Bell, BriefcaseBusiness, CheckCircle2, ChevronRight, CircleDollarSign, LayoutDashboard, ListChecks, Menu, Moon, Plus, Sparkles, Target, Trash2, X } from 'lucide-react'
import { initialLifeState, type LifeState } from './types'
import { loadLifeState, saveLifeState } from './lib/storage'
import { formatTime, formatTodayLabel } from './lib/date'

const navItems = [
  { label: 'Overview', icon: LayoutDashboard }, { label: 'Goals', icon: Target }, { label: 'Tasks', icon: ListChecks },
  { label: 'Money', icon: CircleDollarSign }, { label: 'Career', icon: BriefcaseBusiness }, { label: 'Analytics', icon: BarChart3 },
]

function App() {
  const [active, setActive] = useState('Overview')
  const [menuOpen, setMenuOpen] = useState(false)
  const [state, setState] = useState<LifeState>(() => loadLifeState(initialLifeState))
  const [newTask, setNewTask] = useState('')
  const [showTaskInput, setShowTaskInput] = useState(false)
  const [notice, setNotice] = useState('')
  const [now, setNow] = useState(() => new Date())
  const [showAssistant, setShowAssistant] = useState(false)

  useEffect(() => saveLifeState(state), [state])
  useEffect(() => { const timer = window.setInterval(() => setNow(new Date()), 30000); return () => window.clearInterval(timer) }, [])
  useEffect(() => { if (!notice) return; const timer = window.setTimeout(() => setNotice(''), 2600); return () => window.clearTimeout(timer) }, [notice])

  const completed = useMemo(() => state.tasks.filter((task) => task.completed).length, [state.tasks])
  const focusScore = Math.min(100, 70 + completed * 6)
  const activeGoal = state.goals[0]

  function toggleTask(id: string) { setState((current) => ({ ...current, tasks: current.tasks.map((task) => task.id === id ? { ...task, completed: !task.completed } : task) })) }
  function deleteTask(id: string) { setState((current) => ({ ...current, tasks: current.tasks.filter((task) => task.id !== id) })); setNotice('Task removed') }
  function addTask() {
    const title = newTask.trim(); if (!title) return
    setState((current) => ({ ...current, tasks: [...current.tasks, { id: `task-${Date.now()}`, title, due: 'Today', completed: false, priority: 'medium' }] }))
    setNewTask(''); setShowTaskInput(false); setNotice('Task added successfully')
  }
  function handleAction(label: string) { setActive(label); setMenuOpen(false) }

  function TaskList({ compact = false }: { compact?: boolean }) {
    return <div className="panel task-panel"><div className="panel-head"><h4>{compact ? "Today's tasks" : 'All tasks'}</h4><span>{state.tasks.length} items</span></div>{state.tasks.length === 0 ? <div className="empty-tasks"><CheckCircle2 size={22} /><strong>All clear for today.</strong><span>Add a task when something needs your attention.</span></div> : state.tasks.map((task) => <div className="task-row-wrap" key={task.id}><button className="task-row" onClick={() => toggleTask(task.id)}><CheckCircle2 className={task.completed ? 'done' : 'todo'} size={21} /><div><strong className={task.completed ? 'completed' : ''}>{task.title}</strong><small>{task.due} · {task.priority} priority</small></div></button><button className="delete-task" aria-label={`Delete ${task.title}`} onClick={() => deleteTask(task.id)}><Trash2 size={15} /></button></div>)}{!compact && <button className="add-task" onClick={() => setShowTaskInput(true)}><Plus size={14} /> Add a task</button>}{compact && (showTaskInput ? <div className="task-add-row"><input autoFocus value={newTask} onChange={(event) => setNewTask(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter') addTask(); if (event.key === 'Escape') setShowTaskInput(false) }} placeholder="What needs to be done?" /><button onClick={addTask}>Add</button></div> : <button className="add-task" onClick={() => setShowTaskInput(true)}><Plus size={14} /> Add a task</button>)}</div>
  }

  function PageContent() {
    if (active === 'Tasks') return <><section className="section-heading"><div><span className="eyebrow">TASK MANAGEMENT</span><h3>Everything you need to finish</h3></div></section><section className="content-grid"><TaskList /><div className="panel ai-panel"><div className="ai-icon"><Sparkles size={18} /></div><span className="eyebrow">FOCUS</span><h4>{completed} of {state.tasks.length} tasks completed.</h4><p>Complete one important task at a time and keep your momentum visible.</p><button className="primary-button" onClick={() => setNotice(`Focus score is ${focusScore}`)}>Check my progress <ArrowUpRight size={16} /></button></div><div className="panel stat-card"><div className="stat-heading"><span>TODAY'S FOCUS</span><Target size={17} /></div><strong>{focusScore}</strong><div className="progress"><i style={{ width: `${focusScore}%` }} /></div><p>Keep going</p><span className="muted">Your score updates from completed tasks.</span></div></section></>

    if (active === 'Goals') return <><section className="section-heading"><div><span className="eyebrow">GOAL TRACKER</span><h3>Build the life you are aiming for</h3></div></section><section className="content-grid"><div className="panel"><div className="panel-head"><h4>Active goal</h4><Target size={17} /></div><div className="money-value">{activeGoal?.progress ?? 0}%</div><div className="progress"><i style={{ width: `${activeGoal?.progress ?? 0}%` }} /></div><h4 style={{ marginTop: 22 }}>{activeGoal?.title ?? 'Create your first goal'}</h4><p className="muted">{completed} of {state.tasks.length} tasks complete today. Your daily actions move this goal forward.</p></div><div className="panel ai-panel"><div className="ai-icon"><Target size={18} /></div><span className="eyebrow">NEXT MOVE</span><h4>Turn your goal into today's priority.</h4><p>Choose a task that directly supports your main goal and complete it before moving on.</p><button className="primary-button" onClick={() => handleAction('Tasks')}>Open tasks <ArrowUpRight size={16} /></button></div><div className="panel"><div className="panel-head"><h4>Goal health</h4><span>Live</span></div><div className="money-value">{focusScore}</div><span className="muted">Focus score</span><div className="money-row"><span>Completed</span><strong>{completed}</strong></div><div className="money-row"><span>Remaining</span><strong>{Math.max(0, state.tasks.length - completed)}</strong></div></div></section></>

    if (active === 'Money') return <><section className="section-heading"><div><span className="eyebrow">FINANCE</span><h3>Your money at a glance</h3></div></section><section className="content-grid"><div className="panel money-panel"><div className="panel-head"><h4>Available this month</h4><CircleDollarSign size={17} /></div><div className="money-value">{state.money.currency} {state.money.available.toLocaleString()}</div><div className="money-row"><span>Spent</span><strong>{state.money.currency} {state.money.spent.toLocaleString()}</strong></div><div className="money-row"><span>Saved</span><strong>{state.money.currency} {state.money.saved.toLocaleString()}</strong></div></div><div className="panel"><div className="panel-head"><h4>Saving rate</h4><span>Current</span></div><div className="money-value">{state.money.available ? Math.round((state.money.saved / state.money.available) * 100) : 0}%</div><p className="muted">Keep your saved amount visible and make deliberate spending decisions.</p></div><div className="panel ai-panel"><div className="ai-icon"><CircleDollarSign size={18} /></div><span className="eyebrow">MONEY HABIT</span><h4>Protect your future self.</h4><p>Review spending regularly and keep your savings goal connected to your bigger LifeOS plan.</p></div></section></>

    if (active === 'Career') return <><section className="section-heading"><div><span className="eyebrow">CAREER</span><h3>Build a stronger career</h3></div></section><section className="content-grid"><div className="panel ai-panel"><div className="ai-icon"><BriefcaseBusiness size={18} /></div><span className="eyebrow">CAREER FOCUS</span><h4>Build skills that compound.</h4><p>Use your daily tasks as small steps toward a stronger professional future.</p><button className="primary-button" onClick={() => handleAction('Tasks')}>Set a career task <Plus size={15} /></button></div><div className="panel"><div className="panel-head"><h4>Career progress</h4><span>Today</span></div><div className="money-value">{focusScore}%</div><div className="progress"><i style={{ width: `${focusScore}%` }} /></div><p className="muted">Your focus score reflects completed actions.</p></div><div className="panel"><div className="panel-head"><h4>Next action</h4><BriefcaseBusiness size={17} /></div><p style={{ marginTop: 24, lineHeight: 1.7 }}>Choose one practical skill to improve this week, then create a task for it.</p></div></section></>

    if (active === 'Analytics') return <><section className="section-heading"><div><span className="eyebrow">INSIGHTS</span><h3>See how your actions are trending</h3></div></section><section className="content-grid"><div className="panel"><div className="panel-head"><h4>Task completion</h4><BarChart3 size={17} /></div><div className="money-value">{completed}/{state.tasks.length}</div><div className="progress"><i style={{ width: `${state.tasks.length ? (completed / state.tasks.length) * 100 : 0}%` }} /></div><p className="muted">Completed tasks today</p></div><div className="panel"><div className="panel-head"><h4>Focus score</h4><span>Live</span></div><div className="money-value">{focusScore}</div><p className="muted">Calculated from your completed priorities.</p></div><div className="panel ai-panel"><div className="ai-icon"><BarChart3 size={18} /></div><span className="eyebrow">LIFEOS INSIGHT</span><h4>Consistency beats intensity.</h4><p>Keep completing meaningful actions. Your analytics will become more useful as your history grows.</p></div></section></>

    return <><section className="hero-grid"><div className="hero-card"><div><span className="pill">YOUR DAY AT A GLANCE</span><h2>Make today<br /><em>count.</em></h2><p>Three focused priorities. One clear direction. LifeOS keeps the important things in view.</p></div><div className="focus-score"><span>FOCUS SCORE</span><strong>{focusScore}</strong><small>Live from your tasks</small></div></div><div className="stat-card"><div className="stat-heading"><span>GOAL PROGRESS</span><Target size={17} /></div><strong>{activeGoal?.progress ?? 0}%</strong><div className="progress"><i style={{ width: `${activeGoal?.progress ?? 0}%` }} /></div><p>{activeGoal?.title ?? 'Create your first goal'}</p><span className="muted">{completed} of {state.tasks.length} tasks complete today</span></div></section><section className="section-heading"><div><span className="eyebrow">TODAY</span><h3>Your priorities</h3></div><button className="text-button" onClick={() => handleAction('Tasks')}>View planner <ChevronRight size={16} /></button></section><section className="content-grid"><TaskList compact /><div className="panel ai-panel"><div className="ai-icon"><Sparkles size={18} /></div><span className="eyebrow">LIFEOS INTELLIGENCE</span><h4>A smarter way to plan your day.</h4><p>Your goals, schedule and progress work together. Get a practical plan instead of another list to manage.</p><button className="primary-button" onClick={() => setShowAssistant(true)}>Plan my day <ArrowUpRight size={16} /></button></div><div className="panel money-panel"><div className="panel-head"><h4>Money snapshot</h4><CircleDollarSign size={17} /></div><div className="money-value">{state.money.currency} {state.money.available.toLocaleString()}</div><span className="muted">Available this month</span><div className="money-row"><span>Spent</span><strong>{state.money.currency} {state.money.spent.toLocaleString()}</strong></div><div className="money-row"><span>Saved</span><strong>{state.money.currency} {state.money.saved.toLocaleString()}</strong></div></div></section></>
  }

  return <div className="app-shell">
    {notice && <div className="toast"><CheckCircle2 size={16} />{notice}</div>}
    {showAssistant && <div className="assistant-modal" role="dialog" aria-modal="true" aria-label="LifeOS assistant"><div className="assistant-box"><button className="assistant-close" aria-label="Close assistant" onClick={() => setShowAssistant(false)}><X size={18} /></button><div className="ai-icon"><Sparkles size={18} /></div><span className="eyebrow">LIFEOS INTELLIGENCE</span><h3>Your planning assistant is ready.</h3><p>Start with one clear priority. LifeOS will keep your tasks, goals and money snapshot together.</p><div className="assistant-actions"><button className="primary-button" onClick={() => { setShowAssistant(false); setActive('Tasks'); setShowTaskInput(true); setNotice('Ready to add your next priority') }}>Add a priority <Plus size={15} /></button><button className="assistant-secondary" onClick={() => { setShowAssistant(false); setNotice(`${completed} of ${state.tasks.length} tasks completed today`) }}>Review my progress</button></div></div></div>}
    <aside className={menuOpen ? 'sidebar open' : 'sidebar'}>
      <div className="brand-row"><img className="brand-logo" src="/lifeos-logo.svg" alt="LifeOS" /><span>LifeOS</span><button className="close-menu" onClick={() => setMenuOpen(false)}><X size={18} /></button></div>
      <div className="workspace-label">PERSONAL WORKSPACE</div>
      <nav>{navItems.map(({ label, icon: Icon }) => <button key={label} className={active === label ? 'nav-item active' : 'nav-item'} onClick={() => handleAction(label)}><Icon size={18} /><span>{label}</span></button>)}</nav>
      <div className="sidebar-bottom"><button className="nav-item" onClick={() => setNotice('Reminders are ready')}><Bell size={18} /><span>Reminders</span></button><button className="nav-item" onClick={() => setNotice('Appearance settings are ready')}><Moon size={18} /><span>Appearance</span></button><div className="profile-mini"><div className="avatar">HK</div><div><strong>My workspace</strong><small>Personal account</small></div></div></div>
    </aside>
    <main className="main-content">
      <header className="topbar"><button className="menu-button" onClick={() => setMenuOpen(true)}><Menu size={20} /></button><div><div className="eyebrow">{formatTodayLabel(now).toUpperCase()} · {formatTime(now)} · {active.toUpperCase()}</div><h1>{active === 'Overview' ? 'Good morning.' : active}</h1></div><button className="assistant-button" onClick={() => setShowAssistant(true)}><Sparkles size={17} /> Ask LifeOS <ArrowUpRight size={15} /></button></header>
      {PageContent()}
    </main>
  </div>
}

export default App
